#!/usr/bin/env python3
"""Inventory C function definitions without a compiler or third-party packages.

This is a source inventory, not a preprocessor: inactive #if branches are listed,
and function bodies generated by function-like macros cannot be discovered.
"""

from __future__ import annotations

import argparse
from bisect import bisect_right
from collections import Counter
from dataclasses import asdict, dataclass
import json
from pathlib import Path
import re
import sys
from typing import Callable


LEX = re.compile(
    r"(?P<directive>^[ \t]*\#(?:\\\r?\n|[^\n])*(?:\n|$))"
    r"|(?P<comment>/\*[\s\S]*?\*/|//[^\n]*)"
    r"|(?P<literal>\"(?:\\[\s\S]|[^\"\\])*\"|'(?:\\[\s\S]|[^'\\])*')"
    r"|(?P<space>\s+)"
    r"|(?P<word>[A-Za-z_][A-Za-z_0-9]*)"
    r"|(?P<punct>.)",
    re.MULTILINE,
)
IDENT = re.compile(r"^[A-Za-z_][A-Za-z_0-9]*$")
NON_NAMES = set("""
    void char short int long float double signed unsigned bool _Bool
    struct union enum const volatile restrict static extern inline typedef
    auto register _Atomic _Alignas _Noreturn typeof typeof_unqual __typeof__ __typeof
    __attribute__ __attribute __declspec asm __asm__ _Static_assert
    static_assert alignas sizeof _Generic if for while switch
""".split())
LAYERS = {"core", "game", "platform"}


@dataclass(frozen=True)
class Token:
    text: str
    start: int
    end: int


@dataclass(frozen=True)
class Function:
    path: str
    line: int
    end_line: int
    layer: str
    name: str
    signature: str
    static: bool
    inline: bool
    prefix_ok: bool | None


def lex(source: str) -> list[Token]:
    return [Token(m.group(), m.start(), m.end()) for m in LEX.finditer(source)
            if m.lastgroup not in {"directive", "comment", "space"}]


IncludeMacros = Callable[[str, dict[str, str], set[str]], None]


def update_macros(directive: str, macros: dict[str, str], macro_names: set[str],
                  include: IncludeMacros | None = None) -> None:
    define = re.match(r"\s*#\s*define\s+([A-Za-z_]\w*)(?!\w)(.*)", directive, re.DOTALL)
    undef = re.match(r"\s*#\s*undef\s+([A-Za-z_]\w*)", directive)
    header = re.match(r'\s*#\s*include\s+"([^"\n]+)"', directive)
    if define:
        name, replacement = define[1], define[2]
        if replacement.startswith("("):
            macro_names.add(name)
            macros.pop(name, None)
        else:
            macros[name] = replacement.replace("\\\r\n", " ").replace("\\\n", " ").strip()
            macro_names.discard(name)
    elif undef:
        macros.pop(undef[1], None)
        macro_names.discard(undef[1])
    elif header and include:
        include(header[1], macros, macro_names)


def qualifiers(tokens: list[Token], name: str, macros: dict[str, str]) -> set[str]:
    # Only declaration specifiers can supply function storage qualifiers.
    # In particular, `int f(int values[static 4])` has external linkage.
    prefix = tokens[:next(i for i, token in enumerate(tokens) if token.text == name)]

    def expand(items: list[Token], active: frozenset[str] = frozenset()) -> list[Token]:
        result = []
        for token in items:
            if token.text in macros and token.text not in active:
                result.extend(expand(lex(macros[token.text]), active | {token.text}))
            else:
                result.append(token)
        return result

    words, depth = set(), 0
    for token in expand(prefix):
        if token.text in {"(", "["}:
            depth += 1
        elif token.text in {")", "]"}:
            depth -= 1
        elif depth == 0:
            words.add(token.text)
    return words


def normalized_signature(source: str) -> str:
    pieces = []
    space = False
    for m in LEX.finditer(source):
        if m.lastgroup in {"comment", "directive", "space"}:
            space = True
        else:
            pieces.append((" " if space and pieces else "") + m.group())
            space = False
    return "".join(pieces)


def function_name(tokens: list[Token], macro_names: set[str] | None = None) -> str | None:
    """Find the function declarator, excluding aggregates and variable initializers.

    Parameter lists and attributes are skipped as balanced groups. Parenthesized
    pointer-return declarators are entered, e.g. int (*factory(void))(int).
    """
    if not tokens or tokens[0].text == "typedef":
        return None
    depth = 0
    for token in tokens:
        if token.text == "(" or token.text == "[":
            depth += 1
        elif token.text == ")" or token.text == "]":
            depth -= 1
        elif token.text == "=" and depth == 0:
            return None
    groups = {"__attribute__", "__attribute", "__declspec", "_Alignas", "alignas",
              "_Atomic", "typeof", "typeof_unqual", "__typeof__", "__typeof", "__asm__", "asm"}
    groups.update(macro_names or ())
    i = 0
    while i + 1 < len(tokens):
        name = tokens[i].text
        if tokens[i + 1].text == "(" and IDENT.match(name):
            # An attribute is not a function; neither are return types followed
            # by a pointer declarator. A real parameter list cannot start '*'.
            if name not in NON_NAMES and name not in groups and i > 0 and (
                    i + 2 >= len(tokens) or tokens[i + 2].text != "*"):
                return name
            if name in groups:
                j, nesting = i + 1, 0
                while j < len(tokens):
                    nesting += (tokens[j].text == "(") - (tokens[j].text == ")")
                    j += 1
                    if nesting == 0:
                        break
                i = j
                continue
        # C23 attributes can themselves contain function-shaped expressions.
        if tokens[i].text == "[" and tokens[i + 1].text == "[":
            i += 2
            while i + 1 < len(tokens) and not (
                    tokens[i].text == "]" and tokens[i + 1].text == "]"):
                i += 1
            i += 2
            continue
        i += 1
    return None


def layer_for(path: str) -> str:
    parts = Path(path).parts
    if "src" in parts:
        index = parts.index("src")
        if index + 2 < len(parts):
            return parts[index + 1]
        return "main"
    return "other"


def scan(source: str, path: str, macros: dict[str, str] | None = None,
         macro_names: set[str] | None = None,
         include: IncludeMacros | None = None) -> list[Function]:
    tokens = lex(source)
    macros = dict(macros or {})
    macro_names = set(macro_names or ())
    directives = [m for m in LEX.finditer(source) if m.lastgroup == "directive"]
    directive_index = 0
    newlines = [i for i, ch in enumerate(source) if ch == "\n"]
    result = []
    start, depth = 0, 0
    current = None
    layer = layer_for(path)
    for i, token in enumerate(tokens):
        while directive_index < len(directives) and directives[directive_index].start() < token.start:
            update_macros(directives[directive_index].group(), macros, macro_names, include)
            directive_index += 1
        if token.text == "{":
            if depth == 0:
                declaration = tokens[start:i]
                name = function_name(declaration, macro_names)
                words = qualifiers(declaration, name, macros) if name else set()
                current = (declaration, name, token.start, words) if name else None
            depth += 1
        elif token.text == "}":
            depth -= 1
            if depth == 0:
                if current:
                    declaration, name, body_start, words = current
                    # Preserve string literal spacing, strip only comments and directives.
                    raw = source[declaration[0].start:body_start]
                    signature = normalized_signature(raw)
                    result.append(Function(
                        path, bisect_right(newlines, declaration[0].start) + 1,
                        bisect_right(newlines, token.start) + 1, layer, name,
                        signature, "static" in words, "inline" in words,
                        name.startswith(layer + "_") if layer in LAYERS else None))
                current = None
                start = i + 1
        elif token.text == ";" and depth == 0:
            start = i + 1
    return result


def inventory(root: Path, paths: list[Path], include_third_party: bool = False) -> list[Function]:
    files = set()
    for path in paths:
        if not path.exists():
            raise ValueError(f"path does not exist: {path}")
        candidates = path.rglob("*") if path.is_dir() else [path]
        for candidate in candidates:
            if candidate.is_file() and candidate.suffix in {".c", ".h"}:
                if include_third_party or "third_party" not in candidate.parts:
                    files.add(candidate.resolve())
    sources = {path: path.read_text(encoding="utf-8", errors="replace")
               for path in sorted(files)}
    directive_cache = {}

    def include_context(path: Path, active: frozenset[Path]) -> IncludeMacros:
        def import_header(name: str, macros: dict[str, str], macro_names: set[str]) -> None:
            for candidate in (path.parent / name, root / "src" / name):
                header = candidate.resolve()
                if header.is_file():
                    break
            else:
                return
            if header in active:
                return
            if header not in directive_cache:
                if header not in sources:
                    sources[header] = header.read_text(encoding="utf-8", errors="replace")
                directive_cache[header] = [m.group() for m in LEX.finditer(sources[header])
                                           if m.lastgroup == "directive"]
            nested = include_context(header, active | {header})
            for directive in directive_cache[header]:
                update_macros(directive, macros, macro_names, nested)
        return import_header

    result = []
    # Includes contribute macro context, but do not change the requested file set.
    for path in sorted(files):
        source = sources[path]
        try:
            display = path.relative_to(root).as_posix()
        except ValueError:
            display = path.as_posix()
        result.extend(scan(source, display, include=include_context(path, frozenset({path}))))
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", nargs="*", type=Path,
                        help="C/H files or directories; defaults to src (relative to --root)")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--include-third-party", action="store_true")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    parser.add_argument("--layer", choices=("core", "game", "platform", "main", "third_party", "other"))
    parser.add_argument("--check-prefix", action="store_true",
                        help="check all definitions, including static helpers; exit 1 on a violation")
    args = parser.parse_args()
    root = args.root.resolve()
    paths = [p if p.is_absolute() else root / p for p in (args.paths or [Path("src")])]
    try:
        functions = inventory(root, paths, args.include_third_party)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    if args.layer:
        functions = [f for f in functions if f.layer == args.layer]
    violations = [f for f in functions if f.prefix_ok is False]
    if args.format == "json":
        print(json.dumps([asdict(f) for f in functions], indent=2))
    else:
        for f in functions:
            scope = "static" if f.static else "external"
            flag = " [prefix!]" if args.check_prefix and f.prefix_ok is False else ""
            print(f"{f.path}:{f.line}\t{f.layer}\t{scope}\t{f.signature}{flag}")
        counts = ", ".join(f"{layer}={count}" for layer, count in sorted(
            Counter(f.layer for f in functions).items()))
        print(f"\n{len(functions)} definitions ({counts})")
    if args.check_prefix:
        print(f"{len(violations)} layer-prefix violations", file=sys.stderr)
    return int(args.check_prefix and bool(violations))


if __name__ == "__main__":
    sys.exit(main())
