/*
 * Linux platform backend: Wayland window + EGL/OpenGL context + xkb input.
 *
 * Implements the window/input half of platform.h. Window management uses the
 * xdg-shell stable protocol (its client glue is generated by wayland-scanner in
 * build.sh). The GL context is created via EGL on a wl_egl_window. Keyboard
 * handling decodes keysyms and UTF-8 text through libxkbcommon and implements
 * key repeat client-side (Wayland leaves that to clients); pointer handling
 * tracks motion, buttons and the scroll wheel.
 *
 * PLATFORM_WINDOW_HEADLESS skips the Wayland surface entirely and creates a
 * pbuffer-backed context; the renderer then draws into an offscreen target.
 */

#include "platform.h"

#include <wayland-client.h>
#include <wayland-cursor.h>
#include <wayland-egl.h>
#include <EGL/egl.h>
#include <xkbcommon/xkbcommon.h>

#include "xdg-shell-client-protocol.h"
#include "xdg-decoration-unstable-v1-client-protocol.h"

#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#ifndef XKB_KEY_XF86AudioPlay
#define XKB_KEY_XF86AudioPlay 0x1008FF14
#endif
#ifndef XKB_KEY_XF86AudioPause
#define XKB_KEY_XF86AudioPause 0x1008FF31
#endif
#ifndef XKB_KEY_XF86AudioNext
#define XKB_KEY_XF86AudioNext 0x1008FF17
#endif
#ifndef XKB_KEY_XF86AudioPrev
#define XKB_KEY_XF86AudioPrev 0x1008FF16
#endif

struct Platform_Window {
    /* wayland core */
    struct wl_display    *display;
    struct wl_registry   *registry;
    struct wl_compositor *compositor;
    struct wl_seat       *seat;
    struct wl_shm        *shm;
    struct xdg_wm_base   *wm_base;
    struct wl_surface    *surface;
    struct xdg_surface   *xdg_surface;
    struct xdg_toplevel  *xdg_toplevel;

    struct zxdg_decoration_manager_v1   *decor_manager;
    struct zxdg_toplevel_decoration_v1  *toplevel_decor;

    /* input devices */
    struct wl_keyboard   *keyboard;
    struct wl_pointer    *pointer;
    struct wl_surface    *cursor_surface;
    struct wl_cursor_theme *cursor_theme;
    struct wl_cursor      *cursors[PLATFORM_CURSOR_COUNT];
    Platform_Cursor        cursor_kind;
    uint32_t               pointer_enter_serial;
    uint32_t               last_input_serial;
    b32                    pointer_focused;
    b32                    keyboard_focused;
    struct xkb_context   *xkb_ctx;
    struct xkb_keymap    *xkb_keymap;
    struct xkb_state     *xkb_state;

    /* egl */
    struct wl_egl_window *egl_window;
    EGLDisplay            egl_display;
    EGLContext            egl_context;
    EGLSurface            egl_surface;
    EGLConfig             egl_config;

    u32 width, height;
    u32 pending_w, pending_h;
    u32 flags;
    b32 headless;
    b32 should_close;
    b32 configured;
    b32 maximized;
    b32 any_event;

    /* live input accumulators (committed into the snapshot on poll) */
    b32 key_down[PLATFORM_KEY_COUNT];
    b32 key_pressed[PLATFORM_KEY_COUNT];
    b32 key_released[PLATFORM_KEY_COUNT];
    b32 ctrl, shift, alt;

    vec2 mouse_pos, last_mouse_pos;
    b32 mouse_down[PLATFORM_MOUSE_BUTTON_COUNT];
    b32 mouse_pressed[PLATFORM_MOUSE_BUTTON_COUNT];
    b32 mouse_released[PLATFORM_MOUSE_BUTTON_COUNT];
    f32 scroll_x, scroll_y;
    b32 scroll_precise;
    b32 axis_is_finger;

    u8  text[64];
    u32 text_len;

    /* key repeat */
    s32 repeat_rate;       /* per second, 0 = disabled */
    s32 repeat_delay_ms;
    Platform_Key repeat_key;
    xkb_keycode_t repeat_keycode;
    f64 repeat_next;
};

static void set_opaque_region(Platform_Window *w);

/* X cursor themes use a few aliases for the same common UI shape. */
static struct wl_cursor *load_theme_cursor(struct wl_cursor_theme *theme,
                                           Platform_Cursor cursor) {
    const char *names[3] = {0};
    switch (cursor) {
        case PLATFORM_CURSOR_DEFAULT:
            names[0] = "default"; names[1] = "left_ptr"; break;
        case PLATFORM_CURSOR_TEXT:
            names[0] = "text"; names[1] = "xterm"; break;
        case PLATFORM_CURSOR_HAND:
            names[0] = "pointer"; names[1] = "hand2"; names[2] = "hand"; break;
        case PLATFORM_CURSOR_MOVE:
            names[0] = "move"; names[1] = "fleur"; names[2] = "all-scroll"; break;
        case PLATFORM_CURSOR_GRAB:
            names[0] = "grab"; names[1] = "openhand"; break;
        case PLATFORM_CURSOR_GRABBING:
            names[0] = "grabbing"; names[1] = "closedhand"; break;
        case PLATFORM_CURSOR_RESIZE_HORIZONTAL:
            names[0] = "ew-resize"; names[1] = "col-resize"; break;
        case PLATFORM_CURSOR_RESIZE_VERTICAL:
            names[0] = "ns-resize"; names[1] = "row-resize"; break;
        case PLATFORM_CURSOR_RESIZE_NWSE:
            names[0] = "nwse-resize"; names[1] = "se-resize"; break;
        case PLATFORM_CURSOR_RESIZE_NESW:
            names[0] = "nesw-resize"; names[1] = "sw-resize"; break;
        case PLATFORM_CURSOR_CROSSHAIR:
            names[0] = "crosshair"; break;
        case PLATFORM_CURSOR_NOT_ALLOWED:
            names[0] = "not-allowed"; names[1] = "circle"; break;
        case PLATFORM_CURSOR_HIDDEN:
        case PLATFORM_CURSOR_COUNT:
            break;
    }
    for (u32 i = 0; i < CORE_ARRAY_COUNT(names) && names[i]; i++) {
        struct wl_cursor *result = wl_cursor_theme_get_cursor(theme, names[i]);
        if (result) return result;
    }
    return 0;
}

static void apply_cursor(Platform_Window *w) {
    if (!w->pointer || !w->pointer_focused) return;

    if (w->cursor_kind == PLATFORM_CURSOR_HIDDEN) {
        wl_pointer_set_cursor(w->pointer, w->pointer_enter_serial, 0, 0, 0);
        return;
    }

    struct wl_cursor *cursor = w->cursors[w->cursor_kind];
    if (!cursor) cursor = w->cursors[PLATFORM_CURSOR_DEFAULT];
    if (!cursor || !cursor->image_count || !w->cursor_surface) return;

    struct wl_cursor_image *image = cursor->images[0];
    struct wl_buffer *buffer = wl_cursor_image_get_buffer(image);
    if (!buffer) return;

    wl_pointer_set_cursor(w->pointer, w->pointer_enter_serial,
                          w->cursor_surface, image->hotspot_x, image->hotspot_y);
    wl_surface_attach(w->cursor_surface, buffer, 0, 0);
    wl_surface_damage(w->cursor_surface, 0, 0, image->width, image->height);
    wl_surface_commit(w->cursor_surface);
}

/* ---- keysym -> Platform_Key ---- */

static Platform_Key map_keysym(xkb_keysym_t sym) {
    switch (sym) {
        case XKB_KEY_Escape:       return PLATFORM_KEY_ESCAPE;
        case XKB_KEY_Return:
        case XKB_KEY_KP_Enter:     return PLATFORM_KEY_ENTER;
        case XKB_KEY_space:        return PLATFORM_KEY_SPACE;
        case XKB_KEY_Tab:
        case XKB_KEY_ISO_Left_Tab: return PLATFORM_KEY_TAB;
        case XKB_KEY_BackSpace:    return PLATFORM_KEY_BACKSPACE;
        case XKB_KEY_Delete:       return PLATFORM_KEY_DELETE;
        case XKB_KEY_Home:         return PLATFORM_KEY_HOME;
        case XKB_KEY_End:          return PLATFORM_KEY_END;
        case XKB_KEY_Page_Up:      return PLATFORM_KEY_PAGE_UP;
        case XKB_KEY_Page_Down:    return PLATFORM_KEY_PAGE_DOWN;
        case XKB_KEY_Left:         return PLATFORM_KEY_LEFT;
        case XKB_KEY_Right:        return PLATFORM_KEY_RIGHT;
        case XKB_KEY_Up:           return PLATFORM_KEY_UP;
        case XKB_KEY_Down:         return PLATFORM_KEY_DOWN;
        case XKB_KEY_F1:           return PLATFORM_KEY_F1;
        case XKB_KEY_comma:        return PLATFORM_KEY_COMMA;
        case XKB_KEY_F2:           return PLATFORM_KEY_F2;
        case XKB_KEY_XF86AudioPlay:
        case XKB_KEY_XF86AudioPause: return PLATFORM_KEY_MEDIA_PLAY_PAUSE;
        case XKB_KEY_XF86AudioNext: return PLATFORM_KEY_MEDIA_NEXT;
        case XKB_KEY_XF86AudioPrev: return PLATFORM_KEY_MEDIA_PREV;
        default: break;
    }
    if (sym >= XKB_KEY_a && sym <= XKB_KEY_z)
        return (Platform_Key)(PLATFORM_KEY_A + (sym - XKB_KEY_a));
    if (sym >= XKB_KEY_A && sym <= XKB_KEY_Z)
        return (Platform_Key)(PLATFORM_KEY_A + (sym - XKB_KEY_A));
    return PLATFORM_KEY_UNKNOWN;
}

/* ---- xdg_wm_base ping ---- */

static void wm_base_ping(void *data, struct xdg_wm_base *wm, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wm, serial);
}
static const struct xdg_wm_base_listener wm_base_listener = { .ping = wm_base_ping };

/* ---- xdg_surface / toplevel ---- */

static void xdg_surface_configure(void *data, struct xdg_surface *xs, uint32_t serial) {
    Platform_Window *w = data;
    xdg_surface_ack_configure(xs, serial);
    /* Apply the size from the matching toplevel.configure now that it's acked. */
    if (w->pending_w && w->pending_h &&
        (w->pending_w != w->width || w->pending_h != w->height)) {
        w->width = w->pending_w;
        w->height = w->pending_h;
        if (w->egl_window) {
            wl_egl_window_resize(w->egl_window, (int)w->width, (int)w->height, 0, 0);
            set_opaque_region(w);
        }
    }
    w->configured = true;
    w->any_event = true;
}
static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

static void toplevel_configure(void *data, struct xdg_toplevel *tl,
                               int32_t width, int32_t height, struct wl_array *states) {
    (void)tl;
    Platform_Window *w = data;
    w->maximized = false;
    uint32_t *state;
    wl_array_for_each(state, states) {
        if (*state == XDG_TOPLEVEL_STATE_MAXIMIZED || *state == XDG_TOPLEVEL_STATE_FULLSCREEN)
            w->maximized = true;
    }
    if (width > 0 && height > 0) {
        w->pending_w = (u32)width;
        w->pending_h = (u32)height;
    }
}
static void toplevel_close(void *data, struct xdg_toplevel *tl) {
    (void)tl;
    ((Platform_Window *)data)->should_close = true;
}
static void toplevel_bounds(void *d, struct xdg_toplevel *t, int32_t w, int32_t h) {
    (void)d; (void)t; (void)w; (void)h;
}
static void toplevel_caps(void *d, struct xdg_toplevel *t, struct wl_array *c) {
    (void)d; (void)t; (void)c;
}
static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = toplevel_configure,
    .close     = toplevel_close,
    .configure_bounds = toplevel_bounds,
    .wm_capabilities = toplevel_caps,
};

/* ---- xdg-decoration ---- */

static void decor_configure(void *data, struct zxdg_toplevel_decoration_v1 *d,
                            uint32_t mode) {
    (void)data; (void)d; (void)mode;
}
static const struct zxdg_toplevel_decoration_v1_listener decor_listener = {
    .configure = decor_configure,
};

/* ---- keyboard ---- */

static void kb_keymap(void *data, struct wl_keyboard *kb, uint32_t format,
                      int32_t fd, uint32_t size) {
    (void)kb;
    Platform_Window *w = data;
    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) { close(fd); return; }

    char *map = mmap(0, size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (map == MAP_FAILED) { close(fd); return; }

    struct xkb_keymap *keymap = xkb_keymap_new_from_string(
        w->xkb_ctx, map, XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS);
    munmap(map, size);
    close(fd);
    if (!keymap) return;

    if (w->xkb_keymap) xkb_keymap_unref(w->xkb_keymap);
    if (w->xkb_state)  xkb_state_unref(w->xkb_state);
    w->xkb_keymap = keymap;
    w->xkb_state  = xkb_state_new(keymap);
}

static void kb_enter(void *data, struct wl_keyboard *kb, uint32_t serial,
                     struct wl_surface *surf, struct wl_array *keys) {
    (void)kb; (void)surf; (void)keys;
    Platform_Window *w = data;
    w->keyboard_focused = true;
    w->last_input_serial = serial;
    w->any_event = true;
}
static void kb_leave(void *data, struct wl_keyboard *kb, uint32_t serial,
                     struct wl_surface *surf) {
    (void)kb; (void)serial; (void)surf;
    Platform_Window *w = data;
    memset(w->key_down, 0, sizeof(w->key_down)); /* release all on focus loss */
    w->ctrl = w->shift = w->alt = false;
    w->repeat_key = PLATFORM_KEY_UNKNOWN;
    w->repeat_keycode = 0;
    w->keyboard_focused = false;
    w->any_event = true;
}

static void append_text_for(Platform_Window *w, xkb_keycode_t keycode) {
    char buf[16];
    int n = xkb_state_key_get_utf8(w->xkb_state, keycode, buf, sizeof(buf));
    if (n <= 0 || (unsigned char)buf[0] < 0x20 || buf[0] == 0x7F) return;
    if (w->ctrl || w->alt) return; /* shortcuts are not text */
    if (w->text_len + (u32)n <= sizeof(w->text)) {
        memcpy(w->text + w->text_len, buf, (size_t)n);
        w->text_len += (u32)n;
    }
}

static void kb_key(void *data, struct wl_keyboard *kb, uint32_t serial,
                   uint32_t time, uint32_t key, uint32_t state) {
    (void)kb; (void)time;
    Platform_Window *w = data;
    if (!w->xkb_state) return;
    w->last_input_serial = serial;
    w->any_event = true;

    /* libinput/evdev keycodes are offset by 8 from xkb keycodes. */
    xkb_keycode_t keycode = key + 8;
    xkb_keysym_t sym = xkb_state_key_get_one_sym(w->xkb_state, keycode);
    b32 pressed = (state == WL_KEYBOARD_KEY_STATE_PRESSED);

    Platform_Key pk = map_keysym(sym);
    if (pk != PLATFORM_KEY_UNKNOWN) {
        w->key_down[pk] = pressed;
        if (pressed) w->key_pressed[pk] = true;
        else         w->key_released[pk] = true;
    }

    if (pressed) {
        append_text_for(w, keycode);
        if (w->repeat_rate > 0 && xkb_keymap_key_repeats(w->xkb_keymap, keycode)) {
            w->repeat_key = pk;
            w->repeat_keycode = keycode;
            w->repeat_next = platform_time_seconds() + w->repeat_delay_ms / 1000.0;
        }
    } else if (keycode == w->repeat_keycode) {
        w->repeat_key = PLATFORM_KEY_UNKNOWN;
        w->repeat_keycode = 0;
    }
}

static void kb_modifiers(void *data, struct wl_keyboard *kb, uint32_t serial,
                         uint32_t dep, uint32_t lat, uint32_t lck, uint32_t group) {
    (void)kb; (void)serial;
    Platform_Window *w = data;
    if (!w->xkb_state) return;
    xkb_state_update_mask(w->xkb_state, dep, lat, lck, 0, 0, group);
    w->ctrl  = xkb_state_mod_name_is_active(w->xkb_state, XKB_MOD_NAME_CTRL,  XKB_STATE_MODS_EFFECTIVE) > 0;
    w->shift = xkb_state_mod_name_is_active(w->xkb_state, XKB_MOD_NAME_SHIFT, XKB_STATE_MODS_EFFECTIVE) > 0;
    w->alt   = xkb_state_mod_name_is_active(w->xkb_state, XKB_MOD_NAME_ALT,   XKB_STATE_MODS_EFFECTIVE) > 0;
}
static void kb_repeat(void *data, struct wl_keyboard *kb, int32_t rate, int32_t delay) {
    (void)kb;
    Platform_Window *w = data;
    w->repeat_rate = rate;
    w->repeat_delay_ms = delay;
}
static const struct wl_keyboard_listener keyboard_listener = {
    .keymap = kb_keymap, .enter = kb_enter, .leave = kb_leave,
    .key = kb_key, .modifiers = kb_modifiers, .repeat_info = kb_repeat,
};

/* ---- pointer ---- */

static void ptr_enter(void *data, struct wl_pointer *p, uint32_t serial,
                      struct wl_surface *surf, wl_fixed_t sx, wl_fixed_t sy) {
    (void)p; (void)surf;
    Platform_Window *w = data;
    w->pointer_enter_serial = serial;
    w->pointer_focused = true;
    w->mouse_pos = vec2_make((f32)wl_fixed_to_double(sx), (f32)wl_fixed_to_double(sy));
    w->last_mouse_pos = w->mouse_pos;
    w->any_event = true;
    apply_cursor(w);
}
static void ptr_leave(void *data, struct wl_pointer *p, uint32_t serial,
                      struct wl_surface *surf) {
    (void)p; (void)serial; (void)surf;
    Platform_Window *w = data;
    w->pointer_focused = false;
    w->any_event = true;
}
static void ptr_motion(void *data, struct wl_pointer *p, uint32_t time,
                       wl_fixed_t sx, wl_fixed_t sy) {
    (void)p; (void)time;
    Platform_Window *w = data;
    w->mouse_pos = vec2_make((f32)wl_fixed_to_double(sx), (f32)wl_fixed_to_double(sy));
    w->any_event = true;
}
static void ptr_button(void *data, struct wl_pointer *p, uint32_t serial,
                       uint32_t time, uint32_t button, uint32_t state) {
    (void)p; (void)time;
    Platform_Window *w = data;
    b32 down = (state == WL_POINTER_BUTTON_STATE_PRESSED);
    w->last_input_serial = serial;
    w->any_event = true;
    /* Linux input-event-codes: BTN_LEFT=0x110, RIGHT=0x111, MIDDLE=0x112 */
    Platform_MouseButton b;
    switch (button) {
        case 0x110: b = PLATFORM_MOUSE_LEFT;   break;
        case 0x111: b = PLATFORM_MOUSE_RIGHT;  break;
        case 0x112: b = PLATFORM_MOUSE_MIDDLE; break;
        default: return;
    }
    w->mouse_down[b] = down;
    if (down) w->mouse_pressed[b] = true;
    else      w->mouse_released[b] = true;
}
static void ptr_axis(void *data, struct wl_pointer *p, uint32_t time,
                     uint32_t axis, wl_fixed_t value) {
    (void)p; (void)time;
    Platform_Window *w = data;
    f32 v = (f32)wl_fixed_to_double(value);
    /* Wayland axis: 0 = vertical scroll, 1 = horizontal. Positive = down/right.
       A wheel notch is ~10 surface units, so we report "lines". */
    if (axis == 0) w->scroll_y -= v / 10.0f;
    else           w->scroll_x -= v / 10.0f;
    if (w->axis_is_finger) w->scroll_precise = true;
    w->any_event = true;
}
static void ptr_frame(void *data, struct wl_pointer *p) { (void)data; (void)p; }
static void ptr_axis_source(void *d, struct wl_pointer *p, uint32_t s) {
    (void)p;
    Platform_Window *w = d;
    w->axis_is_finger = (s == WL_POINTER_AXIS_SOURCE_FINGER || s == WL_POINTER_AXIS_SOURCE_CONTINUOUS);
}
static void ptr_axis_stop(void *d, struct wl_pointer *p, uint32_t t, uint32_t a) { (void)d;(void)p;(void)t;(void)a; }
static void ptr_axis_discrete(void *d, struct wl_pointer *p, uint32_t a, int32_t v) { (void)d;(void)p;(void)a;(void)v; }
static void ptr_axis_value120(void *d, struct wl_pointer *p, uint32_t a, int32_t v) { (void)d;(void)p;(void)a;(void)v; }
static void ptr_axis_rel_dir(void *d, struct wl_pointer *p, uint32_t a, uint32_t dir) { (void)d;(void)p;(void)a;(void)dir; }
static const struct wl_pointer_listener pointer_listener = {
    .enter = ptr_enter, .leave = ptr_leave, .motion = ptr_motion,
    .button = ptr_button, .axis = ptr_axis, .frame = ptr_frame,
    .axis_source = ptr_axis_source, .axis_stop = ptr_axis_stop,
    .axis_discrete = ptr_axis_discrete, .axis_value120 = ptr_axis_value120,
    .axis_relative_direction = ptr_axis_rel_dir,
};

/* ---- seat ---- */

static void seat_caps(void *data, struct wl_seat *seat, uint32_t caps) {
    Platform_Window *w = data;
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !w->keyboard) {
        w->keyboard = wl_seat_get_keyboard(seat);
        wl_keyboard_add_listener(w->keyboard, &keyboard_listener, w);
    }
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !w->pointer) {
        w->pointer = wl_seat_get_pointer(seat);
        wl_pointer_add_listener(w->pointer, &pointer_listener, w);
    }
}
static void seat_name(void *d, struct wl_seat *s, const char *n) { (void)d;(void)s;(void)n; }
static const struct wl_seat_listener seat_listener = {
    .capabilities = seat_caps, .name = seat_name,
};

/* ---- registry ---- */

static void registry_global(void *data, struct wl_registry *reg, uint32_t name,
                            const char *iface, uint32_t version) {
    Platform_Window *w = data;
    if (strcmp(iface, wl_compositor_interface.name) == 0) {
        w->compositor = wl_registry_bind(reg, name, &wl_compositor_interface,
                                         version < 4 ? version : 4);
    } else if (strcmp(iface, wl_shm_interface.name) == 0) {
        w->shm = wl_registry_bind(reg, name, &wl_shm_interface, 1);
    } else if (strcmp(iface, xdg_wm_base_interface.name) == 0) {
        w->wm_base = wl_registry_bind(reg, name, &xdg_wm_base_interface, version < 5 ? version : 5);
        xdg_wm_base_add_listener(w->wm_base, &wm_base_listener, w);
    } else if (strcmp(iface, wl_seat_interface.name) == 0) {
        w->seat = wl_registry_bind(reg, name, &wl_seat_interface,
                                   version < 5 ? version : 5);
        wl_seat_add_listener(w->seat, &seat_listener, w);
    } else if (strcmp(iface, zxdg_decoration_manager_v1_interface.name) == 0) {
        w->decor_manager = wl_registry_bind(reg, name,
                                            &zxdg_decoration_manager_v1_interface, 1);
    }
}
static void registry_remove(void *d, struct wl_registry *r, uint32_t n) { (void)d;(void)r;(void)n; }
static const struct wl_registry_listener registry_listener = {
    .global = registry_global, .global_remove = registry_remove,
};

/* ---- EGL setup ---- */

static b32 egl_create_context(Platform_Window *w, EGLint surface_bit) {
    if (!eglInitialize(w->egl_display, 0, 0)) return false;
    eglBindAPI(EGL_OPENGL_API);

    EGLint cfg_attrs[] = {
        EGL_SURFACE_TYPE, surface_bit,
        EGL_RENDERABLE_TYPE, EGL_OPENGL_BIT,
        EGL_RED_SIZE, 8, EGL_GREEN_SIZE, 8, EGL_BLUE_SIZE, 8, EGL_ALPHA_SIZE, 8,
        EGL_NONE
    };
    EGLint num = 0;
    if (!eglChooseConfig(w->egl_display, cfg_attrs, &w->egl_config, 1, &num) || num == 0)
        return false;

    EGLint ctx_attrs[] = {
        EGL_CONTEXT_MAJOR_VERSION, 4,
        EGL_CONTEXT_MINOR_VERSION, 6,
        EGL_CONTEXT_OPENGL_PROFILE_MASK, EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT,
        EGL_NONE
    };
    w->egl_context = eglCreateContext(w->egl_display, w->egl_config, EGL_NO_CONTEXT, ctx_attrs);
    if (w->egl_context == EGL_NO_CONTEXT) {
        EGLint fallback[] = { EGL_CONTEXT_MAJOR_VERSION, 4, EGL_NONE };
        w->egl_context = eglCreateContext(w->egl_display, w->egl_config, EGL_NO_CONTEXT, fallback);
        if (w->egl_context == EGL_NO_CONTEXT) return false;
    }
    return true;
}

static b32 egl_setup(Platform_Window *w) {
    w->egl_display = eglGetDisplay((EGLNativeDisplayType)w->display);
    if (w->egl_display == EGL_NO_DISPLAY) return false;
    if (!egl_create_context(w, EGL_WINDOW_BIT)) return false;

    w->egl_window = wl_egl_window_create(w->surface, (int)w->width, (int)w->height);
    if (!w->egl_window) return false;

    w->egl_surface = eglCreateWindowSurface(w->egl_display, w->egl_config,
                                            (EGLNativeWindowType)w->egl_window, 0);
    if (w->egl_surface == EGL_NO_SURFACE) return false;

    if (!eglMakeCurrent(w->egl_display, w->egl_surface, w->egl_surface, w->egl_context))
        return false;

    eglSwapInterval(w->egl_display, 1);
    return true;
}

static b32 egl_setup_headless(Platform_Window *w) {
    w->egl_display = eglGetDisplay(EGL_DEFAULT_DISPLAY);
    if (w->egl_display == EGL_NO_DISPLAY) return false;
    if (!egl_create_context(w, EGL_PBUFFER_BIT)) return false;
    EGLint pb_attrs[] = { EGL_WIDTH, 16, EGL_HEIGHT, 16, EGL_NONE };
    w->egl_surface = eglCreatePbufferSurface(w->egl_display, w->egl_config, pb_attrs);
    if (w->egl_surface == EGL_NO_SURFACE) return false;
    return eglMakeCurrent(w->egl_display, w->egl_surface, w->egl_surface, w->egl_context);
}

/* Opaque region lets the compositor skip blending behind us. With a
   transparent (rounded-corner) window it must stay unset while windowed; a
   maximized window is square, so it can be opaque again. */
static void set_opaque_region(Platform_Window *w) {
    if (!w->compositor || !w->surface) return;
    if ((w->flags & PLATFORM_WINDOW_TRANSPARENT) && !w->maximized) {
        wl_surface_set_opaque_region(w->surface, 0);
        return;
    }
    struct wl_region *region = wl_compositor_create_region(w->compositor);
    wl_region_add(region, 0, 0, (int)w->width, (int)w->height);
    wl_surface_set_opaque_region(w->surface, region);
    wl_region_destroy(region);
}

/* ---- public API ---- */

Platform_Window *platform_window_open(const char *title, const char *app_id,
                                      u32 width, u32 height, u32 flags) {
    Platform_Window *w = calloc(1, sizeof(*w));
    if (!w) return 0;
    w->width = width;
    w->height = height;
    w->flags = flags;
    w->repeat_rate = 25;
    w->repeat_delay_ms = 400;

    if (flags & PLATFORM_WINDOW_HEADLESS) {
        w->headless = true;
        w->configured = true;
        w->keyboard_focused = true;
        if (!egl_setup_headless(w)) {
            fprintf(stderr, "[platform] headless EGL setup failed\n");
            platform_window_close(w);
            return 0;
        }
        return w;
    }

    w->display = wl_display_connect(0);
    if (!w->display) {
        fprintf(stderr, "[platform] cannot connect to Wayland display\n");
        free(w);
        return 0;
    }

    w->xkb_ctx = xkb_context_new(XKB_CONTEXT_NO_FLAGS);

    w->registry = wl_display_get_registry(w->display);
    wl_registry_add_listener(w->registry, &registry_listener, w);
    wl_display_roundtrip(w->display); /* bind globals */
    wl_display_roundtrip(w->display); /* seat caps     */

    if (!w->compositor || !w->wm_base) {
        fprintf(stderr, "[platform] missing wl_compositor / xdg_wm_base\n");
        platform_window_close(w);
        return 0;
    }

    w->surface = wl_compositor_create_surface(w->compositor);
    w->cursor_surface = wl_compositor_create_surface(w->compositor);
    if (w->shm) {
        const char *size_env = getenv("XCURSOR_SIZE");
        int cursor_size = size_env ? atoi(size_env) : 24;
        if (cursor_size <= 0) cursor_size = 24;
        w->cursor_theme = wl_cursor_theme_load(getenv("XCURSOR_THEME"), cursor_size, w->shm);
        if (w->cursor_theme) {
            for (u32 i = 0; i < PLATFORM_CURSOR_COUNT; i++)
                w->cursors[i] = load_theme_cursor(w->cursor_theme, (Platform_Cursor)i);
        }
    }
    w->xdg_surface = xdg_wm_base_get_xdg_surface(w->wm_base, w->surface);
    xdg_surface_add_listener(w->xdg_surface, &xdg_surface_listener, w);
    w->xdg_toplevel = xdg_surface_get_toplevel(w->xdg_surface);
    xdg_toplevel_add_listener(w->xdg_toplevel, &toplevel_listener, w);
    xdg_toplevel_set_title(w->xdg_toplevel, title ? title : "app");
    xdg_toplevel_set_app_id(w->xdg_toplevel, app_id ? app_id : "app");
    xdg_toplevel_set_min_size(w->xdg_toplevel, 720, 480);

    /* Ask for server-side decorations only when requested; otherwise tell the
       compositor explicitly that we draw our own chrome. */
    if (w->decor_manager) {
        w->toplevel_decor = zxdg_decoration_manager_v1_get_toplevel_decoration(
            w->decor_manager, w->xdg_toplevel);
        zxdg_toplevel_decoration_v1_add_listener(w->toplevel_decor, &decor_listener, w);
        zxdg_toplevel_decoration_v1_set_mode(w->toplevel_decor,
            (w->flags & PLATFORM_WINDOW_DECORATED) ? ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE
                                                   : ZXDG_TOPLEVEL_DECORATION_V1_MODE_CLIENT_SIDE);
    }

    wl_surface_commit(w->surface);
    /* wait for the first configure before creating the EGL surface */
    while (!w->configured)
        wl_display_dispatch(w->display);

    if (!egl_setup(w)) {
        fprintf(stderr, "[platform] EGL setup failed\n");
        platform_window_close(w);
        return 0;
    }

    set_opaque_region(w);
    wl_surface_commit(w->surface);

    return w;
}

void platform_window_close(Platform_Window *w) {
    if (!w) return;
    if (w->egl_display != EGL_NO_DISPLAY && w->egl_display) {
        eglMakeCurrent(w->egl_display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
        if (w->egl_surface) eglDestroySurface(w->egl_display, w->egl_surface);
        if (w->egl_context) eglDestroyContext(w->egl_display, w->egl_context);
        eglTerminate(w->egl_display);
    }
    if (w->egl_window) wl_egl_window_destroy(w->egl_window);
    if (w->cursor_surface) wl_surface_destroy(w->cursor_surface);
    if (w->cursor_theme) wl_cursor_theme_destroy(w->cursor_theme);
    if (w->toplevel_decor) zxdg_toplevel_decoration_v1_destroy(w->toplevel_decor);
    if (w->decor_manager)  zxdg_decoration_manager_v1_destroy(w->decor_manager);
    if (w->xkb_state)  xkb_state_unref(w->xkb_state);
    if (w->xkb_keymap) xkb_keymap_unref(w->xkb_keymap);
    if (w->xkb_ctx)    xkb_context_unref(w->xkb_ctx);
    if (w->xdg_toplevel) xdg_toplevel_destroy(w->xdg_toplevel);
    if (w->xdg_surface)  xdg_surface_destroy(w->xdg_surface);
    if (w->surface)      wl_surface_destroy(w->surface);
    if (w->display)      wl_display_disconnect(w->display);
    free(w);
}

b32 platform_window_should_close(Platform_Window *w) { return w->should_close; }
void platform_window_request_close(Platform_Window *w) { w->should_close = true; }

/* Synthesize auto-repeat events that came due since the last poll. */
static void run_key_repeat(Platform_Window *w) {
    if (!w->repeat_keycode || w->repeat_rate <= 0 || !w->xkb_state) return;
    f64 now = platform_time_seconds();
    f64 interval = 1.0 / (f64)w->repeat_rate;
    u32 guard = 0;
    while (now >= w->repeat_next && guard++ < 8) {
        if (w->repeat_key != PLATFORM_KEY_UNKNOWN) w->key_pressed[w->repeat_key] = true;
        append_text_for(w, w->repeat_keycode);
        w->repeat_next += interval;
        w->any_event = true;
    }
    if (now >= w->repeat_next) w->repeat_next = now + interval;
}

void platform_poll_events(Platform_Window *w, Platform_Input *in) {
    if (!w->headless) {
        wl_display_dispatch_pending(w->display);
        /* read anything already on the socket without blocking */
        if (wl_display_prepare_read(w->display) == 0) {
            struct pollfd pfd = { .fd = wl_display_get_fd(w->display), .events = POLLIN };
            if (poll(&pfd, 1, 0) > 0) wl_display_read_events(w->display);
            else wl_display_cancel_read(w->display);
        }
        wl_display_dispatch_pending(w->display);
        wl_display_flush(w->display);
        run_key_repeat(w);
    }

    memset(in, 0, sizeof(*in));

    memcpy(in->key_down, w->key_down, sizeof(in->key_down));
    memcpy(in->key_pressed, w->key_pressed, sizeof(in->key_pressed));
    memcpy(in->key_released, w->key_released, sizeof(in->key_released));
    memset(w->key_pressed, 0, sizeof(w->key_pressed));
    memset(w->key_released, 0, sizeof(w->key_released));
    in->ctrl = w->ctrl; in->shift = w->shift; in->alt = w->alt;

    memcpy(in->mouse_down, w->mouse_down, sizeof(in->mouse_down));
    memcpy(in->mouse_pressed, w->mouse_pressed, sizeof(in->mouse_pressed));
    memcpy(in->mouse_released, w->mouse_released, sizeof(in->mouse_released));
    memset(w->mouse_pressed, 0, sizeof(w->mouse_pressed));
    memset(w->mouse_released, 0, sizeof(w->mouse_released));

    in->mouse_pos   = w->mouse_pos;
    in->mouse_delta = vec2_sub(w->mouse_pos, w->last_mouse_pos);
    in->mouse_inside = w->pointer_focused || w->headless;
    w->last_mouse_pos = w->mouse_pos;

    in->scroll_x = w->scroll_x;
    in->scroll_y = w->scroll_y;
    in->scroll_precise = w->scroll_precise;
    w->scroll_x = w->scroll_y = 0;
    w->scroll_precise = false;

    if (w->text_len) {
        memcpy(in->text, w->text, w->text_len);
        in->text_len = w->text_len;
        w->text_len = 0;
    }

    in->focused = w->keyboard_focused;
    in->any_event = w->any_event;
    w->any_event = false;
}

void platform_wait_events(Platform_Window *w, f64 timeout_s) {
    if (w->headless || timeout_s <= 0) return;
    /* Wake early for a pending key repeat. */
    if (w->repeat_keycode) {
        f64 until = w->repeat_next - platform_time_seconds();
        if (until < timeout_s) timeout_s = CORE_MAX(until, 0.0);
    }
    while (wl_display_prepare_read(w->display) != 0)
        wl_display_dispatch_pending(w->display);
    wl_display_flush(w->display);
    struct pollfd pfd = { .fd = wl_display_get_fd(w->display), .events = POLLIN };
    int ms = (int)(timeout_s * 1000.0 + 0.5);
    if (poll(&pfd, 1, ms) > 0) wl_display_read_events(w->display);
    else wl_display_cancel_read(w->display);
    wl_display_dispatch_pending(w->display);
}

void platform_window_set_cursor(Platform_Window *w, Platform_Cursor cursor) {
    if (!w) return;
    if (cursor >= PLATFORM_CURSOR_COUNT) cursor = PLATFORM_CURSOR_DEFAULT;
    if (w->cursor_kind == cursor) return;
    w->cursor_kind = cursor;
    apply_cursor(w);
}

void platform_swap_buffers(Platform_Window *w) {
    if (w->headless) return;
    eglSwapBuffers(w->egl_display, w->egl_surface);
}

void platform_window_size(Platform_Window *w, u32 *out_w, u32 *out_h) {
    if (out_w) *out_w = w->width;
    if (out_h) *out_h = w->height;
}

void platform_window_begin_move(Platform_Window *w) {
    if (w->headless || !w->seat) return;
    xdg_toplevel_move(w->xdg_toplevel, w->seat, w->last_input_serial);
    /* The compositor owns the pointer until the drag ends; the release never
       reaches us, so don't leave the button stuck down. */
    w->mouse_down[PLATFORM_MOUSE_LEFT] = false;
}

void platform_window_begin_resize(Platform_Window *w, Platform_Edge edge) {
    if (w->headless || !w->seat || edge == PLATFORM_EDGE_NONE) return;
    static const u32 map[] = {
        [PLATFORM_EDGE_TOP] = XDG_TOPLEVEL_RESIZE_EDGE_TOP,
        [PLATFORM_EDGE_BOTTOM] = XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM,
        [PLATFORM_EDGE_LEFT] = XDG_TOPLEVEL_RESIZE_EDGE_LEFT,
        [PLATFORM_EDGE_RIGHT] = XDG_TOPLEVEL_RESIZE_EDGE_RIGHT,
        [PLATFORM_EDGE_TOP_LEFT] = XDG_TOPLEVEL_RESIZE_EDGE_TOP_LEFT,
        [PLATFORM_EDGE_TOP_RIGHT] = XDG_TOPLEVEL_RESIZE_EDGE_TOP_RIGHT,
        [PLATFORM_EDGE_BOTTOM_LEFT] = XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_LEFT,
        [PLATFORM_EDGE_BOTTOM_RIGHT] = XDG_TOPLEVEL_RESIZE_EDGE_BOTTOM_RIGHT,
    };
    xdg_toplevel_resize(w->xdg_toplevel, w->seat, w->last_input_serial, map[edge]);
    w->mouse_down[PLATFORM_MOUSE_LEFT] = false;
}

void platform_window_minimize(Platform_Window *w) {
    if (w->headless) return;
    xdg_toplevel_set_minimized(w->xdg_toplevel);
}

void platform_window_toggle_maximize(Platform_Window *w) {
    if (w->headless) return;
    if (w->maximized) xdg_toplevel_unset_maximized(w->xdg_toplevel);
    else              xdg_toplevel_set_maximized(w->xdg_toplevel);
}

b32 platform_window_is_maximized(Platform_Window *w) { return w->maximized; }

Core_GlLoadProc platform_gl_loader(Platform_Window *w) {
    (void)w;
    return (Core_GlLoadProc)eglGetProcAddress;
}
